### ISSUE TITLE
ERD 문서의 오류 수정

### ISSUE THREAD

**Issue by djkeh** [djkeh/fastcampus-project-board#132]
패스트캠퍼스 질문게시판에 질문자분께서 게시판 프로젝트 erd 문서의 오류를 찾아 제보해 주셨다.
해당 내용을 이슈로 정리하고, 필요할 경우 고치도록 한다.

## Todo

* [x] `article_hashtag` 테이블의 잘못된 `article_id`, `hashtag_id` 자료형을 수정하기
* [x] `article_comment` 테이블의 잘못된 `user_account_id` 자료형을 수정하기
* [x] `user_account` 테이블의 `email` uk 설계와 실제 엔티티 설계가 다른 것을 해결하기

## Reference

* https://fastcampus.co.kr/qna/211368/read/15046
