### ISSUE TITLE
[테스트 데이터 생성기] README.md 업데이트

### ISSUE THREAD

**Issue by djkeh** [djkeh/fastcampus-project-board#147]
현재 게시판 서비스 프로젝트의 `README.md` 파일은 "10개 프로젝트로 완성하는 백엔드 웹개발" 강의를 기준으로 작성되어 있다.
이제 "10개 프로젝트로 시작하는 백엔드 웹개발" 강의에서 이 프로젝트를 활용한 강의를 진행할 예정이므로,
`README.md` 문서를 적절히 업데이트 해준다.

## Todo

* [x] "10개 프로젝트로 시작하는 백엔드 웹개발" 강의 정보 소개
* [x] 개발 환경 세부 버전 업데이트
* [x] 데모 페이지 삭제: 데모 페이지는 인프라 유지비용이 발생하기 때문에, "10개 프로젝트로 완성하는 백엔드 웹개발" 출시 2년이 지났으므로 데모 서비스 종료 결정
* [x] 질문 페이지 정보에 "10개 프로젝트로 시작하는 백엔드 웹개발" 질문 페이지 소개
